### ISSUE TITLE
Extract source map validator as a library

### ISSUE THREAD

**Issue by connorjclark** [getsentry/sourcemaps.io#41]
Would be very useful to have this as a module to use in a CI / test environment. https://github.com/ben-ng/sourcemap-validator isn't ideal because it only returns the first error, and also I believe the implementation here is more detailed.

**Comment by connorjclark** [comment]
I plan to add a new audit in [Lighthouse](https://github.com/GoogleChrome/lighthouse) that displays all the source map validation errors for a given page.

I haven't had a chance to explore the source code here yet, but supposing I fork and expose the validation code as a library, would this repo consider merging my changes and publishing a package?

**Comment by cmanallen** [comment]
Hi Connor, we're clearing out our backlog and seeing as this is four years old with minimal activity its a realistic assumption that Sentry will never prioritize this. However, if you think its valuable please re-open this issue and I'll see if we can find someone within Sentry to take on this project.
