### ISSUE TITLE
Support analyzing all source maps for a given URL

### ISSUE THREAD

**Issue by connorjclark** [getsentry/sourcemaps.io#59]
It'd be very convenient if this tool could take a URL to a webpage and give source map results for every resource found on it.

There's a couple ways to do it:

* headless chrome + puppeteer: grab all the scripts loaded on the page, fetch the code, look for source map url
* use Lighthouse with `-G` and load `.SourceMaps` from the artifacts written to disk. This is also using headless chrome, but Lighthouse does all the heavy lifting for you.

**Comment by cmanallen** [comment]
Hi Connor, we're clearing out our backlog and seeing as this is four years old with minimal activity its a realistic assumption that Sentry will never prioritize this.  However, if you think its valuable please re-open this issue and I'll see if we can find someone within Sentry to take on this project.
